# Generated by Django 5.1.8 on 2025-07-16 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_code', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.FileField(blank=True, null=True, upload_to='records')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Records', to='project.calldata')),
            ],
        ),
    ]
