# Generated by Django 5.2 on 2025-04-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldata',
            name='mark',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
