# Generated by Django 5.2 on 2025-04-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_calldata_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldata',
            name='mark',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
