# Generated by Django 5.2 on 2025-04-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_calldata_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldata',
            name='mark',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
