# Generated by Django 5.2 on 2025-04-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_calldata_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldata',
            name='bl',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='group',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='mark',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='photo',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
