# Generated by Django 5.2 on 2025-04-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_calldata_bl_alter_calldata_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldata',
            name='mark',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
