# Generated by Django 5.2 on 2025-04-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_calldata_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldata',
            name='photo',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
