# Generated by Django 5.2 on 2025-04-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_calldata_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldata',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
