# Generated by Django 5.2 on 2025-04-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_calldata_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldata',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
