# Generated by Django 5.2 on 2025-04-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_calldata_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldata',
            name='greeting1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting10',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting3',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting6',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting7',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting8',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting9',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
