# Generated by Django 5.2 on 2025-04-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_alter_calldata_greeting1_alter_calldata_greeting10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldata',
            name='greeting1',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting10',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting2',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting3',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting4',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting5',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting6',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting7',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting8',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting9',
            field=models.IntegerField(default=None),
        ),
    ]
