# Generated by Django 5.2 on 2025-04-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_calldata_cons1_alter_calldata_cons10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldata',
            name='cons1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='cons10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='cons2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='cons3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='cons4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='cons5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='cons6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='cons7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='cons8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='cons9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='greeting9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='hearing1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='hearing10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='hearing2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='hearing3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='hearing4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='hearing5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='hearing6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='hearing7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='hearing8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='hearing9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='interest1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='interest10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='interest2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='interest3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='interest4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='interest5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='interest6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='interest7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='interest8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='interest9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='question1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='question10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='question2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='question3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='question4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='question5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='question6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='question7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='question8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='question9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
