# Generated by Django 5.2 on 2025-04-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_alter_calldata_cons1_alter_calldata_cons10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldata',
            name='dialog1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='emotion1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='emotion10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='emotion2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='emotion3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='emotion4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='emotion5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='emotion6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='emotion7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='emotion8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='emotion9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='note1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='note10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='note2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='note3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='note4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='note5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='note6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='note7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='note8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='note9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='polite1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='polite10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='polite2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='polite3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='polite4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='polite5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='polite6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='polite7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='polite8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='polite9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='solution1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='solution10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='solution2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='solution3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='solution4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='solution5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='solution6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='solution7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='solution8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='solution9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='speech1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='speech10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='speech2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='speech3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='speech4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='speech5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='speech6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='speech7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='speech8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='speech9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='warning1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='warning10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='warning2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='warning3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='warning4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='warning5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='warning6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='warning7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='warning8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='warning9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
