# Generated by Django 5.2 on 2025-04-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_calldata_dialog1_alter_calldata_dialog10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calldata',
            name='dialog1',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog10',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog2',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog3',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog4',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog5',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog6',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog7',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog8',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='dialog9',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='mark',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
