# Generated by Django 5.1.8 on 2025-04-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_calldata_photo_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldata',
            name='month',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
