# Generated by Django 5.1.8 on 2025-04-21 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_calldata_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calldata',
            name='month',
        ),
    ]
