# Generated by Django 5.1.8 on 2025-04-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_remove_calldata_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoresForMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Scores For Month +', to='project.calldata')),
            ],
        ),
    ]
