# Generated by Django 5.1.8 on 2025-04-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_scoresformonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresformonth',
            name='call1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='call10',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='call2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='call3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='call4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='call5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='call6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='call7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='call8',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='call9',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='code1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='code10',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='code2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='code3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='code4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='code5',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='code6',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='code7',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='code8',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='code9',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='comment1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='comment10',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='comment2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='comment3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='comment4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='comment5',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='comment6',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='comment7',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='comment8',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='comment9',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='cons1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='cons10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='cons2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='cons3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='cons4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='cons5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='cons6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='cons7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='cons8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='cons9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='dialog1',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='dialog10',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='dialog2',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='dialog3',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='dialog4',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='dialog5',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='dialog6',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='dialog7',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='dialog8',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='dialog9',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='emotion1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='emotion10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='emotion2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='emotion3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='emotion4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='emotion5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='emotion6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='emotion7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='emotion8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='emotion9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='greeting1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='greeting10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='greeting2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='greeting3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='greeting4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='greeting5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='greeting6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='greeting7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='greeting8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='greeting9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='group',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='hearing1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='hearing10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='hearing2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='hearing3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='hearing4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='hearing5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='hearing6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='hearing7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='hearing8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='hearing9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='interest1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='interest10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='interest2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='interest3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='interest4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='interest5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='interest6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='interest7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='interest8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='interest9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='mark',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='mis1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='mis2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='mis3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='month',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='note1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='note10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='note2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='note3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='note4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='note5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='note6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='note7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='note8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='note9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='polite1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='polite10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='polite2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='polite3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='polite4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='polite5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='polite6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='polite7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='polite8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='polite9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='question1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='question10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='question2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='question3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='question4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='question5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='question6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='question7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='question8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='question9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='service1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='service10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='service2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='service3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='service4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='service5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='service6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='service7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='service8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='service9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='solution1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='solution10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='solution2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='solution3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='solution4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='solution5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='solution6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='solution7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='solution8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='solution9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='speech1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='speech10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='speech2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='speech3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='speech4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='speech5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='speech6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='speech7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='speech8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='speech9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='warning1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='warning10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='warning2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='warning3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='warning4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='warning5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='warning6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='warning7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='warning8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='warning9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
