# Generated by Django 5.1.8 on 2025-04-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_scoresformonth_call1_scoresformonth_call10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresformonth',
            name='month',
            field=models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], max_length=2, null=True),
        ),
    ]
