# Generated by Django 5.1.8 on 2025-04-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_alter_scoresformonth_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresformonth',
            name='month',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
