# Generated by Django 5.1.8 on 2025-04-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_alter_scoresformonth_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresformonth',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
