# Generated by Django 5.1.8 on 2025-04-21 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_alter_scoresformonth_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoresForMonth',
        ),
    ]
