# Generated by Django 5.1.8 on 2025-04-21 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_scoresformonth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoresForMonth',
        ),
    ]
