# Generated by Django 5.1.8 on 2025-04-23 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_scoresformonth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoresForMonth',
        ),
    ]
