# Generated by Django 5.1.8 on 2025-04-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_scoresformonth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoresForMonth',
        ),
    ]
