# Generated by Django 5.1.8 on 2025-04-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_scoresformonth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScoresForMonth',
        ),
    ]
