# Generated by Django 5.1.8 on 2025-04-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_scoresformonth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calldata',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='calldata',
            name='photo_hash',
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='bl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='scoresformonth',
            name='photo_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
