# Generated by Django 5.1.8 on 2025-05-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_remove_scoresformonth_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldata',
            name='sikl',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
