# Generated by Django 5.1.8 on 2025-05-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_calldata_sikl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calldata',
            old_name='sikl',
            new_name='month',
        ),
    ]
