# Generated by Django 5.1.8 on 2025-05-06 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_quarterscores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoresformonth',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores_for_month', to='project.calldata'),
        ),
    ]
