# Generated by Django 5.1.8 on 2025-05-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_alter_scoresformonth_operator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=255, verbose_name='Ф.И.О оператора')),
                ('call_code', models.CharField(max_length=50, verbose_name='Код звонка')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('sent_to_google', models.BooleanField(default=False, verbose_name='Отправлено в Google')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
    ]
