# Generated by Django 5.1.8 on 2025-05-27 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
