# Generated by Django 5.1.8 on 2025-05-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Get_Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('call_code', models.IntegerField()),
                ('report', models.TextField()),
            ],
        ),
    ]
