# Generated by Django 5.1.8 on 2025-06-02 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_alter_get_reports_call_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Get_Reports',
        ),
        migrations.DeleteModel(
            name='QuarterScores',
        ),
    ]
