# Generated by Django 5.1.8 on 2025-07-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0049_delete_get_reports_delete_quarterscores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='documents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='documents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
