# Generated by Django 5.1.8 on 2025-07-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0052_management112'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='backgrounds/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='calldata',
            options={'verbose_name': 'Текущий месяц ga ', 'verbose_name_plural': 'Текущий месяц'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'verbose_name': 'Начальство 255 ga ', 'verbose_name_plural': 'Начальство 255'},
        ),
        migrations.AlterModelOptions(
            name='management112',
            options={'verbose_name': 'Начальство 229 ga ', 'verbose_name_plural': 'Начальство 229'},
        ),
        migrations.AlterModelOptions(
            name='schedule1000',
            options={'verbose_name': 'График 1000 ga ', 'verbose_name_plural': 'График 1000'},
        ),
        migrations.AlterModelOptions(
            name='schedule1009',
            options={'verbose_name': 'График 1009 ga ', 'verbose_name_plural': 'График 1009'},
        ),
        migrations.AlterModelOptions(
            name='schedule112',
            options={'verbose_name': 'График 112 ga ', 'verbose_name_plural': 'График 112'},
        ),
        migrations.AlterModelOptions(
            name='scoresformonth',
            options={'verbose_name': 'Архив ga ', 'verbose_name_plural': 'Архив'},
        ),
    ]
